name: Run unit tests on PR
on: 
  pull_request

jobs:
  test:
    name: PHP ${{ matrix.php }} CP ${{ matrix.cp }}
    timeout-minutes: 15
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.0', '7.1', '7.2', '7.3', '7.4' ]
        cp: [ "latest" ]

    services:
      database:
        image: mysql:5.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          extensions: mysql
          coverage: none

      - name: Tool versions
        run: |
          php --version
          composer --version

      - name: Get cached composer directories
        uses: actions/cache@v2
        with:
          path: |
            ./packages
            ./vendor
          key: ${{ runner.os }}-${{ hashFiles('./composer.lock') }}

      - name: Setup and install composer
        run: composer install

      - name: Init DB and CP
        run: ./tests/bin/install.sh cpc_test root root 127.0.0.1 ${{ matrix.cp }}

      - name: Run tests
        run: ./vendor/bin/phpunit -c ./phpunit.xml
